# Generated by Django 5.2.3 on 2025-06-23 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('eligibility_criteria', models.JSONField(default=list)),
                ('required_documents', models.JSONField(default=list)),
                ('deadline', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('village', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('residential_address', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=255)),
                ('graduation_year', models.CharField(max_length=10)),
                ('grades', models.JSONField(default=list)),
                ('transcript_documents', models.FileField(upload_to='results/')),
                ('passport_photo', models.ImageField(upload_to='passports/')),
                ('essay', models.TextField()),
                ('referral_source', models.CharField(blank=True, max_length=255)),
                ('referral_source_confirmed', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_applications', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='api.scholarship')),
            ],
        ),
    ]
