# Generated by Django 5.2.3 on 2025-06-28 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to='passports/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='transcript_documents',
            field=models.FileField(blank=True, null=True, upload_to='results/'),
        ),
    ]
